#!/usr/bin/env node
'use strict';

var _ = require('lodash');
var LamassuConfig = require('lamassu-config');
var promptly = require('promptly');
var psql = process.env.DATABASE_URL || 'postgres://lamassu:lamassu@localhost/lamassu';
var bitjws = require('bitjws-js');


var config = new LamassuConfig(psql);

console.log('\nSetting up De Shared Wallet (desw).\n');
//console.log('Please create your bitjws private key (WIF format).\n');

promptly.prompt('DeSW Server base URL: ', function(urlErr, baseURL) {
  promptly.prompt('DeSW Server key: ', function(keyErr, serverKey) {
    promptly.password('My bitjws wif (private key): ', function(wifErr, wif) {
      updateDb(baseURL, serverKey, wif, function(err) {
        if (err) throw err;
        console.log('\nSuccess.');
      });
    });
  });
});

function updateDb(baseURL, serverKey, wif, cb) {
  var newConfig = {
    exchanges: {
      plugins: {
        coins: {"BTC": true, "DASH": true},
        settings: {
          desw: {
            baseURL: baseURL,
            serverKey: serverKey,
            wif: wif
          }
        },
        current: {
          wallet: 'desw',
          DASHwallet: 'desw',
        }
      }
    }
  };
  config.mergeConfig(newConfig, cb);
}
